### ISSUE TITLE
Sign Up link directs user to chat.susi.ai

### ISSUE THREAD

**Issue by neeraj3029** [fossasia/susi_firefoxbot#149]
**Actual Behaviour**

Current Sign up links directs user to chat.susi.ai, from where user has to open login form from the options and then click on click on Sign Up to open Sign Up form, **which makes the process time consuming.**

**Expected Behaviour**
It would be better if the link leads user directly to the Sign Up form. (https://accounts.susi.ai/signup)

**Steps to reproduce it**

Click on Sign Up link -> Options -> Login -> Sign Up 

**Screenshots of the issue**
GIF:-
![ezgif com-video-to-gif 2](https://user-images.githubusercontent.com/31539812/48301862-57d09d00-e51a-11e8-9bbd-f1a231ddec63.gif)

**Would you like to work on the issue?**
Yes

**Comment by AakashMallik** [comment]
The problem is, Signup is not a route component, hence you will not be able to make the proposed changes happen. This is coming from a guy who has spent a week refactoring the code of Susi_webchat. This will only happen when we prepare a separate component for login and signup, kind of like Facebook or Gmail and the pace at which changes are being accepted into the code base, that might take a long long time. @neeraj3029

**Comment by neeraj3029** [comment]
@AakashMallik I agree that Sign Up us not a route component, that's why I'm proposing Sign Up link to refer to https://accounts.susi.ai/SignUp , instead of https://chat.susi.ai to which will only make the path smaller.

**Comment by AakashMallik** [comment]
> @AakashMallik I agree that Sign Up us not a route component, that's why I'm proposing Sign Up link to refer to https://accounts.susi.ai/SignUp , instead of https://chat.susi.ai to which will only make the path smaller.

Oh, I see. My bad, I probably jumped to conclusions.
